name: shelf_packages_handler
version: 1.0.4

description: A shelf handler for serving a `packages/` directory.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/shelf_packages_handler

environment:
  sdk: '>=1.22.0 <3.0.0'

dependencies:
  async: '>=1.1.0 <3.0.0'
  path: ^1.0.0
  shelf: '>=0.6.0 <0.8.0'
  shelf_static: ^0.2.0
  package_resolver: ^1.0.0

dev_dependencies:
  test: '>=0.12.0 <2.0.0'
